
c               EROS Data Center
c		Shuguang Liu, 11/99


      subroutine depos()


c...Soil is deposited to the system.

c...psloss is the rate of soil loss (kg/m**2/m)
c...bulkd is the bulk density of the soil (kg/liter)
c...edepth is the depth of the soil (m)
c...enrich is the enrichment factor for SOM losses
c...scloss is the total carbon loss from soil organic
c     matter and below ground litter for this month
c...sclosa is the accumulator for scloss

      include 'chrvar.inc'
      include 'comput.inc'
      include 'const.inc'
      include 'param.inc'
      include 'parfx.inc'
      include 'plot1.inc'
      include 'plot2.inc'
      include 'zztim.inc'
      include 'prof.inc'
      include 'timvar.inc'
      include 'wth.inc'
      include 't0par.inc'

 
c...Local variables
      integer   i, mmon
      real      time1, perc, fr, flost, depth
      real temp,temp1,temp2,temp3,temp4,temp5
c...temp1 --- som1c
c...temp2--- som2c
c...temp3--- som3c
c...temp4--- metabolic
c...temp5--- struct
        

      open(unit=25, file='soilerod.out',status='UNKNOWN')

c...Compute soil and carbon deposition rates from a file generated by
c....the erosion run.  Unit: g/m2/month
      read(25,5) time1, mmon, psloss,perc, socmov,
     $    temp1,temp2,temp3,temp4,temp5
5	format (f10.3, i5, 9f10.3)
	
c.... from g Soil/m2/month to kg Soil/m2/month	
      psloss = 1.0*psloss*edratio
      temp = 1.0*edratio
      socmov = temp*socmov
      temp1 = temp*temp1
      temp2 = temp*temp2
      temp3 = temp*temp3
      temp4 = temp*temp4
      temp5 = temp*temp5

      psloss = psloss/1000.0

      flost = psloss/(10.0*lyrden(1)*adep(1)) 
        
      sclosa = sclosa + socmov
c.....first deduct the SOC contained in the soil thickness corresponding
c	to the deposited thickness from the original top layer and 
c	add it to the second

      deadrt(2) = deadrt(2) + (strucc(SOIL)+metabc(SOIL))*flost
      lyrsocp(2,1) = lyrsocp(2,1) + flost*som1c(SOIL)
      lyrsocp(2,2) = lyrsocp(2,2) + flost*som2c
      lyrsocp(2,3) = lyrsocp(2,3) + flost*som3c

c.....substract SOC and nutrients from the top layer
        call soilos(time,nelem,2,flost,som1c(SOIL),som1ci,csrsnk,som1e,
     $              esrsnk)
        call soilos(time,nelem,1,flost,som2c,som2ci,csrsnk,som2e,
     $              esrsnk)
        call soilos(time,nelem,1,flost,som3c,som3ci,csrsnk,som3e,
     $              esrsnk)
        call soilos(time,nelem,2,flost,metabc(SOIL),metcis,csrsnk,
     $              metabe,esrsnk)
        call soilos(time,nelem,2,flost,strucc(SOIL),strcis,csrsnk,
     $              struce,esrsnk)
		
c...calculating the soil depth being deposited to the top layer

      depth = flost * adep(1)
	
      adep(2) = adep(2) + depth

c... if the 2nd layer is thicker than 20 cm then divide this layer into
c	two layers (adep(2) - 20, and 20 cm) for characterizing the change of 
c	temperature and moisture profiles
c	if (time .gt. 1924 .and. time .lt. 1928)  then
c          print *,time, adep(2),lyrsocp(2,1),lyrsocp(2,2),lyrsocp(2,3)
c	endif
	
      if (adep(2) .gt. 20.) then
c	   nlayer = nlayer + 1
         actlayers = actlayers + 1
         if (actlayers .gt. MAXLYR) actlayers = MAXLYR
c	   if (nlayer .gt. MAXLYR) nlayer = MAXLYR
c.....aggregate the buttom two layers first	   
         do 10 i = actlayers, 4, -1
c	   do 10 i = nlayer, 4, -1
         if (i .eq. MAXLYR) then
               lyrden(i) = (lyrden(i)*adep(i) + lyrden(i-1)*adep(i-1))
     $	                     /(adep(i) + adep(i-1)+0.001)
 	         lyrsand(i)=(lyrsand(i)*adep(i)+lyrsand(i-1)*adep(i-1))
     $	                     /(adep(i) + adep(i-1)+0.001)
               lyrclay(i)=(lyrclay(i)*adep(i)+lyrclay(i-1)*adep(i-1))
     $	                     /(adep(i) + adep(i-1)+0.001)
     	         deadrt(i) = deadrt(i) + deadrt(i-1)
      	         livroot(i) = livroot(i) + livroot(i-1)
      	         lyrsocp(i,1) = lyrsocp(i,1) + lyrsocp(i-1,1)
                 lyrsocp(i,2) = lyrsocp(i,2) + lyrsocp(i-1,2)
                 lyrsocp(i,3) = lyrsocp(i,3) + lyrsocp(i-1,3)
	         adep(i) = adep(i) + adep(i-1) 

         else
               adep(i) = adep(i-1)
	         lyrden(i) = lyrden(i-1)
	         lyrsand(i) = lyrsand(i-1)
	         lyrclay(i) = lyrclay(i-1)
	         deadrt(i) = deadrt(i-1)
	         livroot(i) = livroot(i-1)
      	         lyrsocp(i,1) = lyrsocp(i-1,1)
	         lyrsocp(i,2) = lyrsocp(i-1,2)
	         lyrsocp(i,3) = lyrsocp(i-1,3)       
	      endif
10 	   continue

c.......create a new third layer of 20 cm by depth-weighted average
	   lyrden(3) = lyrden(2)
	   lyrsand(3) = lyrsand(2)
	   lyrclay(3) = lyrclay(2)

c.....create a new second layer	   
	   lyrden(2) = (lyrden(2) * (adep(2) - depth)
     $	             + lyrden(1) * (20.0 - (adep(2) - depth)))/20.
	   lyrsand(2) = (lyrsand(2) * (adep(2) - depth)
     $	             + lyrsand(1) * (20. - (adep(2) - depth)))/20.
	   lyrclay(2) = (lyrclay(2) * (adep(2) - depth)
     $	             + lyrclay(1) * (20. - (adep(2) - depth)))/20.

c....save C in layer 3 temporarily
	deadrt(3) = deadrt(2)
	livroot(3) = livroot(2)
	lyrsocp(3,1)=lyrsocp(2,1)
	lyrsocp(3,2)=lyrsocp(2,2)
	lyrsocp(3,3)=lyrsocp(2,3)

c.... separate C
	   adep(2) = adep(2) - 20.
	   fr = adep(2)/(adep(2)+20.)
c.... to layer 2
	   deadrt(2) = deadrt(3) * fr
	   livroot(2) = livroot(3) * fr
	   lyrsocp(2,1) = lyrsocp(3,1) * fr
	   lyrsocp(2,2) = lyrsocp(3,2) * fr
	   lyrsocp(2,3) = lyrsocp(3,3) * fr

c.... to layer 3
	   adep(3) = 20.
	deadrt(3) = deadrt(3) - deadrt(2)
	livroot(3) = livroot(3) - livroot(2)
	lyrsocp(3,1) = lyrsocp(3,1)-lyrsocp(2,1)
	lyrsocp(3,2) = lyrsocp(3,2)-lyrsocp(2,2)
	lyrsocp(3,3) = lyrsocp(3,3)-lyrsocp(2,3)
	   
c	print *
	  
c         print *,time,adep(2),fr,lyrsocp(2,1),lyrsocp(2,2),lyrsocp(2,3)
	endif

c.....add the carbon and nutrients from deposited soil to the top layer
	
c	flost = -socmov/(som1c(SOIL) + som2c + som3c
c     $            + metabc(SOIL) + strucc(SOIL))

	
c.....add SOC and nutrients to the top layer
	flost = -temp1/som1c(SOIL)
        call soilos(time,nelem,2,flost,som1c(SOIL),som1ci,csrsnk,som1e,
     $              esrsnk)
	flost = -temp2/som2c
        call soilos(time,nelem,1,flost,som2c,som2ci,csrsnk,som2e,
     $              esrsnk)
	flost = -temp3/som3c
        call soilos(time,nelem,1,flost,som3c,som3ci,csrsnk,som3e,
     $              esrsnk)
	flost = -temp4/metabc(SOIL)
        call soilos(time,nelem,2,flost,metabc(SOIL),metcis,csrsnk,
     $              metabe,esrsnk)
	flost = -temp5/strucc(SOIL)
        call soilos(time,nelem,2,flost,strucc(SOIL),strcis,csrsnk,
     $              struce,esrsnk)
	
	do 100 i = 1,actlayers 
c	do 100 i = 1, nlayer
	lyrsoc(i)=lyrsocp(i,1)+lyrsocp(i,2)
     $	           +lyrsocp(i,3) + deadrt(i)
c	if (time .lt. 1955 .and. time .gt. 1954) then
c	write(*, 120) time, i,adep(i),lyrsoc(i),lyrsocp(i,1),lyrsocp(i,2),
c     $	           +lyrsocp(i,3), deadrt(i), flost
c	print *, -socmov,som1c(SOIL),som2c, som3c,
c     $             metabc(SOIL),strucc(SOIL)
c	endif
100	continue
120	format(f6.1,i4,10f8.2)
	

	return
	end
