
/*              Copyright 1993 Colorado State University     */
/*                      All Rights Reserved                  */


/*
 *	ferr.c
 *
 *	Handles errors generated by the flow functions.
 */


#include "flow.h"
/*
 *	error messages
 */

static char *err_msg[] = {
	"No Error.",					/* 0 */
	"Stack Overflow",				/* 1 */
	"Value of source variable is negative",		/* 2 */
	"Amount to flow has been limited",		/* 3 */
	};

void
flow_err(int error_num, float when)
{
	fprintf(stderr,
		"\n Century flow error occurred at time = %10.4f\n%s\n\n",
		err_msg[error_num]);
	return;
}
